---
title: "Analysis of Breweries and Beers"
author: "Kevin Thompson and Stuart Miller"
date: "June 14, 2019"
output: slidy_presentation
---

```{r setup, include=FALSE}
library(tidyverse)
library(naniar)
library(cowplot)

knitr::opts_chunk$set(echo = FALSE)
load(file = "analysis/data/.RData")

```


# Missingness
```{r missingness, echo=TRUE}

#missingness and number of beers between states
plot1 <- nabular_data %>%
  group_by(State) %>%
  summarize(num_miss_IBU = n_miss(IBU),
            num_beers = length(unique(Beer_ID))) %>%
  ggplot(aes(x=num_beers, y=num_miss_IBU)) +
  geom_point() +
  labs(title="Missingness of IBU vs Number of Beers in Each State", x="Number of Unique Beers Brewed", y="# Missing IBU Values")

#missingness by style
plot2 <- nabular_data %>%
  group_by(ShortStyle) %>%
  summarize(perc_miss_IBU = prop_miss(IBU),
            num_miss_IBU = n_miss(IBU)) %>%
  filter(num_miss_IBU > 15) %>%
  ggplot(aes(x=reorder(ShortStyle, desc(perc_miss_IBU)), y=perc_miss_IBU)) +
  geom_col() +
  labs(title="Missingness of IBU by Beer Style", x = "Beer Style", y = "% Missing IBU Values")

gA <- ggplotGrob(plot1)
gB <- ggplotGrob(plot2)
grid::grid.newpage()
grid::grid.draw(rbind(gA, gB))

```

***

```{r missByState, echo=TRUE}
merged_data %>%
  group_by(State) %>%
  summarize(num_miss = n_miss(IBU),
            p_miss = prop_miss(IBU)) %>%
  filter(num_miss > 10) %>%
  ggplot(aes(x=reorder(State, desc(p_miss)), y=p_miss)) +
  geom_col() +
  labs(title="IBU - % Missing By State", x="State", y="% IBU Values Missing")

```

***


```{r ABV, echo=TRUE, warning=FALSE}
#Deletes missing data, but this is fine because only 2% of ABV missing out of 2410 obs.

merged_data %>%
  ggplot(aes(x = ABV)) + 
  geom_histogram(bins = 30) +
  labs(title="Distribution of Alcohol By Volume", x="Alcohol By Volume", y="Count")

```

***

```{r comparison, echo=TRUE, warning=FALSE}
merged_data %>%
  ggplot(aes(x=IBU, y=ABV)) +
  geom_point(alpha = 0.1) +
  labs(title = "ABV vs IBU")
```



